name: Android Clean CI

on:
  pull_request:
    branches:
      - main

jobs:
  clean:
    name: Run Gradle clean
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Run Gradle clean
        run: ./gradlew clean
